### ISSUE TITLE
`dladdr1` is not portable

### ISSUE THREAD

**Issue by Torrekie** [LNSSPsd/pv4#1]
For current code I stubbed `dladdr1` calls which requesting a `RTLD_DL_LINKMAP`, this was obviously Glibc-only stuff.

We need alternative method for this since most system provides similar API (e.g. Darwin dyld)

**Comment by LNSSPsd** [comment]
This project isn't supposed to be portable.

**Comment by Torrekie** [comment]
still encountering some local test scenes, shall be mostly portable, but I wonder can we just ignore link_map on other systems and just use `dladdr` as alternative

**Comment by LNSSPsd** [comment]
Yep, module names aren't necessary.
